ManualTeamData = [
  {
    primaryKey: 'wolf-williams-racing',
    wikiLink: '/wiki/Frank_Williams_Racing_Cars#Wolf%E2%80%93Williams_Racing_(1976)',
    name: 'Wolf–Williams Racing',
    base: 'Reading, United Kingdom',
    website: nil,
    constructorChampionships: '0',
    driverChampionships: '0',
    fastestLaps: '0',
    polePositions: '0',
    points: '0',
    podiums: '0',
    victories: '0',
    racesEntered: '16',
    finalEntry: '1976 Japanese Grand Prix',
    firstEntry: '1976 Brazilian Grand Prix',
    engines: 'Ford',
    founders: 'Walter Wolf',
    nextName: 'walter-wolf-racing',
    previousName: 'frank-williams-racing-cars',
    notedDrivers: 'Jacky Ickx, Arturo Merzario, Renzo Zorzi, Michel Leclère, Chris Amon, Warwick Brown, Hans Binder, Masami Kuwashima, Emilio Zapico',
    notedStaff: 'Frank Williams, Harvey Postlethwaite',
    teamPrincipal: nil,
    technicalDirector: nil,
    results2019: nil,
    notes: nil,
  },
  {
    primaryKey: 'coloni-racing',
    wikiLink: '/wiki/Scuderia_Coloni',
    name: 'Scuderia Coloni',
    base: 'Italy',
    website: nil,
    constructorChampionships: '0',
    driverChampionships: '0',
    fastestLaps: '0',
    polePositions: '0',
    points: '0',
    podiums: '0',
    victories: '0',
    racesEntered: '82',
    finalEntry: '1991 Australian Grand Prix',
    firstEntry: '1987 Italian Grand Prix',
    engines: nil,
    founders: 'Enzo Coloni',
    nextName: 'andrea-moda-formula',
    previousName: nil,
    notedDrivers: nil,
    notedStaff: nil,
    teamPrincipal: nil,
    technicalDirector: nil,
    results2019: nil,
    notes: '14 starts',
  },
  {
    primaryKey: 'aston-martin',
    wikiLink: 'wiki/Aston_Martin_in_Formula_One',
    name: 'Aston Martin F1 Team',
    base: 'Newport Pagnell, United Kingdom',
    website: nil,
    constructorChampionships: '0',
    driverChampionships: '0',
    fastestLaps: '0',
    polePositions: '0',
    points: '0',
    podiums: '0',
    victories: '0',
    racesEntered: '6',
    finalEntry: '1960 British Grand Prix',
    firstEntry: '1959 Dutch Grand Prix',
    engines: 'Aston Martin',
    founders: '',
    nextName: nil,
    previousName: 'racing-point-f1-team',
    notedDrivers: 'Roy Salvadori, Carroll Shelby, Maurice Trintignant',
    notedStaff: 'David Brown, Ted Cutting',
    teamPrincipal: nil,
    technicalDirector: nil,
    results2019: nil,
    notes: nil,
  },
]
